### ISSUE TITLE
How might one go about configuring a project to automatically set the title?

### ISSUE THREAD

**Issue by r3wt** [documentationjs/gulp-documentation#13]
I tried with the name option in my project as you can see here:

``` js
gulp.src('./src/app.js')
        .pipe(doc({ format: 'html',name: 'jqMVC' }))
        .pipe(gulp.dest('build/docs'));
```

https://github.com/r3wt/jqMVC/blob/master/gulpfile.js#L53

but title of the generated html page is always `| Documentation`. how can i resolve this to automatically set the title?

**Comment by r3wt** [comment]
bummer, looks like i picked up a dead project.

**Comment by tmcw** [comment]
Not dead, just busy - I have a full-time job as well as many other priorities that need attending to, so I can't respond to every issue every day. I need to update gulp-documentation to documentation v4, and then this will be possible. If that isn't soon enough for you, I'd recommend try it yourself.

**Comment by r3wt** [comment]
I feel ya man. I got a full time job as well. The tragedy of open source. everyone's busy. I'm not a big node guy and i have little experience with gulp, but if i get a chance and the code is pretty sane, there's a chance i'll submit a pr.
