### ISSUE TITLE
The code generator has deoptimised the styling of "..." as it exceeds the max of "100KB"

### ISSUE THREAD

**Issue by mrbormeth** [documentationjs/gulp-documentation#14]
Hey :) 

The documentation gets created as it should, but how can i solve that error?

**Comment by tmcw** [comment]
Hi Morten,

Thanks for the report, and sorry for the delay. This is based on the `compact` option of Babel's parser, which we use for generating ASTs. I'll work on fixing this at the `documentation` level by configuring babelify.

- Tom

**Comment by tmcw** [comment]
Fixed in 3.2.0! Thanks again for reporting this issue, sorry it took a while to ship in a release.
