### ISSUE TITLE
 TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by kevincaradant** [documentationjs/gulp-documentation#17]
Hi,

I get this now but i don't know why :/ , any idea ? 

Thank you :) 
Édit : i use gulp-document 2.2.0,  same  thing with 2.1.0, i tried so many things without success during 2 hours but i dont know why i get This error.  Its mysterious :/

![image](https://cloud.githubusercontent.com/assets/6093175/13093285/cf822ad6-d504-11e5-891e-c6b72a391868.png)

**Comment by JordanMajd** [comment]
+1

**Comment by JordanMajd** [comment]
When I try to use `format: 'html'` I get `cannot read property 'forEach' of undefined`. Yet, when I try to use `format: 'md'` I get `cannot read property 'reduce' of undefined`.

**Comment by ilionic** [comment]
Same problem here, any tips?

**Comment by FuzzySockets** [comment]
I'm having the same issue JordanMajd describes.

**Comment by vabatta** [comment]
+1

**Comment by michaelBenin** [comment]
Also having this problem.

**Comment by esavichev** [comment]
+1

**Comment by tmcw** [comment]
Can anyone share their gulp configuration? Thanks!

**Comment by mattonik** [comment]
Hi!
Having same issue, both md and html.
Using gulp task as described in your documentation:

```
gulp.task('documentation', function () {

  gulp.src('./app.js')
    .pipe(documentation({ format: 'md' }))
    .pipe(gulp.dest('md-documentation'));

});
```

**Comment by riyadhalnur** [comment]
I think upgrading to documentation v4 will solve the problem. I used documentation 4 beta 2 directly from the command line and it works as it should.

**Comment by simon-s9** [comment]
+1
<img width="1382" alt="screen shot 2016-06-09 at 10 47 55" src="https://cloud.githubusercontent.com/assets/14272055/15922306/08c9b566-2e38-11e6-9833-7cd7d11105b9.png">

**Comment by andrewdonskikh** [comment]
+1

**Comment by nrser** [comment]
i hit a similar issue (which searching for led me here). i knew my problem was from `documentation.js` failing at dependency resolution.

adding the `shallow: true` option let me run it successfully. though, of course, it's not resolving the dependencies.

i just installed `documentation.js` and i have a meteor project with funky requires so i have no idea what i'm missing, but this might at least let you run something:

```
gulp.task('doc', () => {
  gulp.src('blah.js')
    .pipe(documentation({shallow: true, format: 'md'}))
    .pipe(gulp.dest('./doc'));
});
```

**Comment by clemsos** [comment]
+1

**Comment by mmclau14** [comment]
+1

**Comment by kevincaradant** [comment]
Hi guys, I know I'm the author of this issue but today, I don't use anymore gulp, so I don't have follow the evolution of this issue. I don't close it but if you think it's good, I let you to close this issue. Good luck ;)

**Comment by kristianmandrup** [comment]
Please update to `"documentation": "^4.0.0-beta11"`
