### ISSUE TITLE
Specify output directory

### ISSUE THREAD

**Issue by jamesryanbell** [documentationjs/gulp-documentation#2]
Hi

Is there a way specify the output directory?

Thanks,
James

**Comment by jseppi** [comment]
`gulp.dest` is where you specify where to to pipe output from this and other gulp plugins.

https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpdestpath-options

**Comment by jamesryanbell** [comment]
sorry you're absolutely right, I had a variable set to the wrong folder!!! Sorry for wasting your time on this, closing the issue now.

Thanks for getting back so quickly though :)
