### ISSUE TITLE
how do i run for all my files?

### ISSUE THREAD

**Issue by nrser** [documentationjs/gulp-documentation#20]
hey, i'm just getting started with documentation.js (and gulp). the README gives examples of generating docs for a single file, but i'd like to generate docs for all my files.

i'm trying

```
gulp.task('doc', () => {
  gulp.src('./meteor/imports/**/*.js')
    .pipe(debug())
    .pipe(documentation({shallow: true, format: 'md'}))
    .pipe(gulp.dest('./doc'));
});
```

and i can _see_ all the files going through from the `debug` output but the result seems to be a single `API.md` for a single file.

i'm using Meteor which has weird imports so the dependency following thing doesn't work (hence this `shallow: true` part).

thanks.

**Comment by tmcw** [comment]
Sure, I'm updating this module to documentation v4 and updating the readme with a multi-file example.

**Comment by rwam** [comment]
It seems your documentation should be updated. When I use

    gulp.task('documentation', function() {
        gulp.src('app/js/**/*.js')
            .pipe(gulpDocumentation({
                format: 'html'
            }))
            .pipe(gulp.dest('docs/api'));
    });
 
I get the following error:

    [10:59:38] Error: invalid format given: valid options are html, md, remark, json
        at module.exports (/…/…/Workspace/pm-wg-angular/node_modules/gulp-documentation/index.js:82:11)
        …

**Comment by rwam** [comment]
And it works only, when the task returns the stream. Otherwise no output is generated ;(

**Comment by tmcw** [comment]
Hi @rwam - the recent version bump to 3.0.0 included a breaking change, along with updated examples. To update to 3.0.0, your code would look like:

```js
gulp.task('documentation', function() {
    gulp.src('app/js/**/*.js')
        .pipe(gulpDocumentation('html'))
        .pipe(gulp.dest('docs/api'));
});
```

That that modified version out and let me know if it still doesn't work with the change.

**Comment by rwam** [comment]
Hi @tmcw – I use version 3.0.0 and yes I tried it as described. But it only write it on the output directory when I use a return statement:

```
gulp.task('documentation', function() {
    return gulp.src('app/js/**/*.js')
        .pipe(gulpDocumentation('html'))
        .pipe(gulp.dest('docs/api'));
});
```
Ok I see the info on the 3.0.0 tag is actual, but it's a little weird ;) There is a missing character:

![bildschirmfoto 2016-11-28 um 13 32 46](https://cloud.githubusercontent.com/assets/2979907/20668476/5ffe07b0-b56f-11e6-8063-247c8fed4832.png)

**Comment by tmcw** [comment]
Thanks for spotting that! I've updated the [code examples](https://github.com/documentationjs/gulp-documentation#api) so they should be functional.
