### ISSUE TITLE
Name inference repeatedly documents the same items

### ISSUE THREAD

**Issue by blaasvaer** [documentationjs/gulp-documentation#22]
All I get is an extremely large file with multiple versions of method names from all modules:

![gulp-jsdoc3](https://cloud.githubusercontent.com/assets/1193257/18642593/952747e4-7ea1-11e6-9548-b0f9c9612fb8.jpg)

How can I actually organize the modules into something readable and well organized (I'm using usejsdoc.org as reference)?

**Comment by tmcw** [comment]
Retitled to something actionable; appreciate the attempt at humor (sarcasm?) but to stay sane and productive we should focus on actionable issues.

Does jsdoc provide correct output? Can you provide an example of the code you're documenting so that we can determine where the issue lies?

**Comment by blaasvaer** [comment]
This is one small module:

    /**
     * This is the entry point for the admin interface
     * 
     * @namespace Index
     * @param  {String}
     * @return {Object} Exports object
     */
    var Index = (function () {
        var _name = 'Papir™ - thee CMS';

        /**
         * Initialize application
         * @memberOf Index
         * @return {void}
         */
        function init () {
            var dashboard = require('dashboard');

            // Set initial Document Title to the name of the app
            document.title = _name;

            addEventListeners();
        }

        /**
         * This is left blank intentionally
         * @memberOf Index
         */
        function addEventListeners () {}

        /**
         * Initialize module Index internally
         */
        init();
    }());

    module.exports = Index;

All other modules are based on the same syntax.

**Comment by blaasvaer** [comment]
It outputs a directory called 'assets' and an index.html file. In the assets directory I find these files:
anchor.js
bass.css
github.css
site.js
style.css

**Comment by tmcw** [comment]
Can you try changing `@memberOf Index` to `@memberof Index`? The [memberof tag](http://usejsdoc.org/tags-memberof.html), like all other JSDoc tags, is all lowercase.

**Comment by blaasvaer** [comment]
OK, that made something of a difference. Am I wrong if I think that it used to be with a capital O?

Well, I guess I'll walk over all the syntax again ... thanks for pointing that out.

**Comment by tmcw** [comment]
I don't believe so, in 2012, before the site moved to usejsdoc.org, it was all lowercase [commit](https://github.com/jsdoc3/jsdoc3.github.com/blob/f7196824f9362c500fa1c7f83804b64dcd72df68/tags-memberof.html)

**Comment by blaasvaer** [comment]
Yeah, but I'm using DocBlockr in Sublime Text 2 / 3 and there it is @memberOf. Even google code has it referenced with an uppercase o:
https://code.google.com/archive/p/jsdoc-toolkit/wikis/TagReference.wiki

Don't know what's going on. It used to work fine with the original gulp-jsdoc with an upper o. I've opened a ticket, asking them to change it to a lower case. We'll see if that will happen. In ST 2 I can change the bugger myself. But due to the change in how packages are managed in ST 3 I can do nothing but wait for 'someone' to do 'something'. That's one of the cons of depending on other peoples code ... I guess it wouldn't make any sense for you to go .toLowerCase() on all @names in gulp-documentation?

**Comment by blaasvaer** [comment]
SOLUTION FOUND: In case any other poor soul is looking for at solution to this:
Install PackageResourceViewer for ST3, and voila, edit the resource yourself.
