### ISSUE TITLE
Pass config and theme options

### ISSUE THREAD

**Issue by dignifiedquire** [documentationjs/gulp-documentation#27]
I'm trying to setup a gulp task which uses the `documentation.yml` from the root of the project and a custom theme, but I can't find a place to pass this option through. It seems these options are not exposed in https://github.com/documentationjs/documentation/blob/master/index.js or am I missing something?

**Comment by tmcw** [comment]
Right now it's not possible to pass a configuration file through gulp-documentation: config loading is done in [sharedInputOptions](https://github.com/documentationjs/documentation/blob/df8efa4d3dee3ee43203e8436ab3d1e203b96529/lib/commands/shared_options.js#L23), which is part of the `documentation` bin, and not exposed in the public API. Given that gulp-documentation and there'll be other kinds of access, maybe we should take an approach like `.babelrc` and parse it by default, even sometimes when it's not what you asked for :)

Or we could just expose a path to `loadConfig` in the Node API path?
