### ISSUE TITLE
Stream is not ended.

### ISSUE THREAD

**Issue by drinchev** [documentationjs/gulp-documentation#3]
Hey there,

I was having problems when I'm using gulp documentation.

The stream seems to not terminate which breaks gulp flow.

```
gulp.task('gdocs', function () {
    return gulp.src('./any.js')
        .pipe(documentation({ format: 'md' }))
        .pipe(gulp.dest('md-documentation'));
});
```

which gives the following output :

```
$ gulp gdocs
[12:59:43] Using gulpfile /Volumes/Media/Projects/Gulpfile.js
[12:59:43] Starting 'gdocs'...
$ 
```

The problem I identified is on [Line 37](https://github.com/documentationjs/gulp-documentation/blob/master/index.js#L37) that needs to have assigned callback. It should look like this :

```
return through2.obj(function document(file, enc, cb) {
   /* ... */
  }, function (callback) {
    /* ... */  
    .pipe(concat(function (output) {
       /* ... */
      cb();
    }));
  });
```

This seems to fix the problem and the callback  is properly called when the stream flushes itself.

**Comment by tmcw** [comment]
@drinchev any chance you can roll a pull request implementing this change?

**Comment by drinchev** [comment]
@tmcw will do this week
